INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (1, 'Rondônia', 'RO');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (2, 'Acre', 'AC');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (3, 'Amazonas', 'AM');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (4, 'Roraima', 'RR');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (5, 'Pará', 'PA');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (6, 'Amapá', 'AP');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (7, 'Tocantins', 'TO');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (8, 'Maranhão', 'MA');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (9, 'Piauí', 'PI');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (10, 'Ceará', 'CE');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (11, 'Rio Grande do Norte', 'RN');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (12, 'Paraíba', 'PB');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (13, 'Pernambuco', 'PE');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (14, 'Alagoas', 'AL');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (15, 'Sergipe', 'SE');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (16, 'Bahia', 'BA');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (17, 'Minas Gerais', 'MG');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (18, 'Espírito Santo', 'ES');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (19, 'Rio de Janeiro', 'RJ');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (20, 'São Paulo', 'SP');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (21, 'Paraná', 'PR');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (22, 'Santa Catarina', 'SC');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (23, 'Rio Grande do Sul', 'RS');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (24, 'Mato Grosso do Sul', 'MS');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (25, 'Mato Grosso', 'MT');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (26, 'Goiás', 'GO');
INSERT INTO `estados`(`id`, `nome`, `sigla`) VALUES (27, 'Distrito Federal', 'DF');
